### ISSUE TITLE
PHP Version Incompatibility w/Classes

### ISSUE THREAD

**Issue by moosetunes** [GrofGraf/laravel-pdf-merger#9]
Hello friends.  Based on my research, it seems I have the error listed below due to a PHP version incompatibility.

Current PHP version : 5.4.452.0

PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in /path_to_file/PDFMerger.php on line 12

I can't change the PHP version so is there a way to change the the code to make this work?

Please advise and thanks in advance.

Steven

**Comment by GrofGraf** [comment]
Hi, 

this package only works with PHP 7.

For PHP 5, I would recommend using the package on top of which this one was created:

https://github.com/Webklex/laravel-pdfmerger

**Comment by moosetunes** [comment]
Will do, thank you.
